### PR TITLE
Closes #7 Closes #10 Closes #12

### LINKED ISSUE #7: Call Mute and Unmute
Remove muted flag and use isOnMute

### LINKED ISSUE #10: Hangup
When not on call you try to transfer the call, hang the call

Uncaught (in promise) m…e.e…s.I…r.exception {code: 2, name: "INVALID_STATE_ERROR", status: 9, message: "Invalid status: 9"}
InviteServerContext.reject @ Session.js:1153InviteServerContext.terminate @ Session.js:1235PhoneLine.cancel @ web-phone.js:857(anonymous function) @ VM1265:2InjectedScript._evaluateOn @ VM842:875InjectedScript._evaluateAndWrap @ VM842:808InjectedScript.evaluate @ VM842:664

Fix the error handling

### LINKED ISSUE #12: Call Answering
When Call reaches voice mail You cannot disconnect the call
Call shows not connected, Cannot cancel/hangup the call, cannot be traces in active call array

The phone keeps ringing even after the call reaches voicemail

When pressed answer this error occurs
Uncaught (in promise) Error: The INFO response status code is: 481 (waiting for 200)(…)

Then when you disconnect the call this error occurs
Sun Feb 07 2016 22:50:17 GMT-0800 (PST) | sip.sipmessage | error parsing "From" header field with value "<sip:@XXXXXXXXX>;tag=434hg6583k"

Remote call doesn't end

Hangup from the phone . The current session in the local ends. The session in the remote doesn't end.

line.cancel() gives this error 
Uncaught m…e.e…s.I…r.exception {code: 2, name: "INVALID_STATE_ERROR", status: 9, message: "Invalid status: 9"}

### PR DESCRIPTION
**Pull request by vyshakhbabji**
1. Added extension for login in demo/index.js and demo/index.html
2. Handled errors for Call Answering, Mute/Unmute, Call, Hangup
Closes #7
Closes #10
Closes #12

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -374,75 +382,139 @@ WebPhone.prototype.onCall = function() {
...
 WebPhone.prototype.hangup = function(line) {
+    try {
+        line = this.getLine(line);
+        this.ua.hangup(line);
+        if (line === this.activeLine) this.activeLine = null;
+        return Promise.resolve(null);
+    }catch (e) {
+        return Promise.reject(e);
+    }
+};
```
Comment (kirill-konshin) [inline src/index.js]: Use Promise constructor

**Comment by vyshakhbabji** [comment]
Closes #7 Closes #10 Closes #12
